# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Подразделения',
                'verbose_name': 'Подразделение',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=25, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=25, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('state', models.BooleanField(choices=[[True, 'Работает'], [False, 'Уволен']], default=True, verbose_name='Состояние')),
                ('position', models.IntegerField(choices=[[1, 'Специалист-эксперт'], [2, 'Ведущий специалист-эксперт'], [3, 'Главный специалист-эксперт'], [4, 'Старший инспектор'], [5, 'Специалист-эксперт (по автоматизации)'], [6, 'Руководитель группы'], [7, 'Заместитель начальника отдела'], [8, 'Начальник отдела'], [9, 'Ведущий специалист-эксперт (юрисконсульт)'], [10, 'Руководитель клиентской службы'], [11, 'Архивариус']], default=1, verbose_name='Должность')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.Department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'verbose_name': 'Сотрудник',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Расположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name_plural': 'Месторасположения',
                'verbose_name': 'Месторасположение',
            },
            managers=[
                ('annotation', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Наименование')),
                ('short_title', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Краткое наименование')),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='enterprise.Organisation', verbose_name='В подчинении')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'verbose_name': 'Организация',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Organisation', verbose_name='Находится в организации'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.Location', verbose_name='Месторасположение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Organisation', verbose_name='Сотрудник организации'),
        ),
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Organisation', verbose_name='Подразделение относится к'),
        ),
    ]
