# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='short_title',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Краткое наименование'),
        ),
    ]
