# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.IntegerField(blank=True, help_text='Инвентарный номер оборудования, допускаются только цифровые идентификаторы', null=True, verbose_name='Инвентарный номер'),
        ),
    ]
