# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20160602_1002'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Серийный номер')),
                ('inventory_number', models.IntegerField(blank=True, null=True, verbose_name='Инвентарный номер')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
                ('revised_at', models.DateTimeField(blank=True, null=True, verbose_name='Ревизия')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentTypes')),
            ],
            options={
                'verbose_name_plural': 'Учётные единицы',
                'verbose_name': 'Оборудование',
                'ordering': ['-created_at'],
            },
        ),
    ]
