# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode', verbose_name='QRCode'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.IntegerField(blank=True, help_text='Инвентарный номер оборудования, допускаются только цифровые идентификаторы', null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(help_text='Марка оборудования, модель или другая информация', max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='responsible',
            field=models.ForeignKey(help_text='Сотрудник ПФР за которым закрепленна техника', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Ответственное лицо'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='revised_at',
            field=models.DateTimeField(blank=True, help_text='Дата проведения последней ревизии', null=True, verbose_name='Ревизия'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Заводской номер оборудования, может содержать цифры и символы, допускается его отсутствие', max_length=25, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(help_text='Выберите к какому типу принадлежит создаваемое оборудование', on_delete=django.db.models.deletion.CASCADE, to='equipment.EquipmentTypes', verbose_name='Тип оборудования'),
        ),
    ]
