# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=50, verbose_name='Surname')),
                ('firstname', models.CharField(max_length=25, verbose_name='First name')),
                ('middlename', models.CharField(max_length=25, verbose_name='Middle name')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('state', models.BooleanField(choices=[[True, 'Work'], [False, 'Fired']], default=True, verbose_name='State')),
                ('position', models.IntegerField(choices=[[1, 'Специалист-эксперт']], default=1, verbose_name='Position')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Emplacement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Organisation')),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisation',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation'),
        ),
        migrations.AddField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation'),
        ),
    ]
