# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160531_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Месторасположение', 'verbose_name_plural': 'Месторасположения'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterField(
            model_name='department',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation', verbose_name='Подразделение относится к'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Location', verbose_name='Месторасположение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(max_length=25, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation', verbose_name='Сотрудник организации'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[[1, 'Специалист-эксперт'], [2, 'Ведущий специалист-эксперт'], [3, 'Старший специалист-эксперт'], [4, 'Специалист-эксперт по делопроизводству'], [5, 'Специалист-эксперт по автоматизации'], [6, 'Руководитель направления'], [7, 'Заместитель начальника отделения'], [8, 'Начальник отделения'], [9, 'Юристконсульт']], default=1, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.BooleanField(choices=[[True, 'Работает'], [False, 'Уволен']], default=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='location',
            name='emplacement',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation', verbose_name='Находится в организации'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Organisation', verbose_name='В подчинении'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='title',
            field=models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Наименование'),
        ),
    ]
