# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20160602_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[[1, 'Специалист-эксперт'], [2, 'Ведущий специалист-эксперт'], [3, 'Главный специалист-эксперт'], [4, 'Старший инспектор'], [5, 'Специалист-эксперт (по автоматизации)'], [6, 'Руководитель группы'], [7, 'Заместитель начальника отдела'], [8, 'Начальник отдела'], [9, 'Ведущий специалист-эксперт (юрисконсульт)'], [10, 'Руководитель клиентской службы'], [11, 'Архивариус']], default=1, verbose_name='Должность'),
        ),
    ]
