# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20160602_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='short_title',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Краткое наименование'),
        ),
    ]
