# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_organisation_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='short_title',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True, verbose_name='Краткое наименование'),
        ),
    ]
