# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 06:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20160607_1300'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('annotation', django.db.models.manager.Manager()),
            ],
        ),
    ]
